wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.4
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1665902191.508296
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 23
      - 34
      4: 3.10.6
      5: 0.13.4
      8:
      - 1
      - 5
